### ISSUE TITLE
Cannot use ::class with dynamic class name 

### ISSUE THREAD

**Issue by MdAnowarHosen** [mikebarlow/megaphone#11]
I'm using laravel 8. I got this error after install megaphone.

```
Symfony\Component\ErrorHandler\Error\FatalError
Cannot use ::class with dynamic class name 
```

**Comment by mikebarlow** [comment]
Could you provide some more information on things like the environment it's running in and the megaphone config file.

Also is this when trying to load the `<livewire:megaphone></livewire:megaphone>` component or when you're trying to send a notification?

I'm inclined to think this will be something environment related as I have megaphone working in a Laravel 8 app currently with no problems at all.

**Comment by 8humayun8** [comment]
Change `$user::class` to `get_class($user)` to get it working in `Megaphone Class`.

**Comment by mikebarlow** [comment]
Ahh, okay. I initially was only supporting PHP8 and thought I'd added that in the Composer file but obviously not.

I'll likely make the change to simply use the `get_class` function as you've mentioned. I'll also update the GitHub Action to test on 7.4 so I can confirm the fix.
