### ISSUE TITLE
Marking unread notification

### ISSUE THREAD

**Issue by Boomchart** [mikebarlow/megaphone#19]
Kindly add a button to all unread notifications as read, like mark all as read.

**Comment by mikebarlow** [comment]
Hey, this is something I've thought about but it's not in my needs right now so I likely won't get to add it just yet.
If you are needing this functionality sooner rather than later though I'll gladly accept a PR for it.

**Comment by titonova** [comment]
@Boomchart titonova/megaphone has implemented this
