### ISSUE TITLE
UI modifications. 

### ISSUE THREAD

**Issue by titonova** [mikebarlow/megaphone#23]
I added a few UI modifications for my project, so I was wondering if you liked them so I could  make a PR for them. (I also added a dark theme):

Light theme:

![image](https://github.com/mikebarlow/megaphone/assets/41286822/6a51e3a0-6476-41ae-92c6-9b4804a8756e)
![image](https://github.com/mikebarlow/megaphone/assets/41286822/40310fc5-875e-43a3-a02f-0916fa262d45)
![image](https://github.com/mikebarlow/megaphone/assets/41286822/bedc4bdb-c6e9-4b68-bc23-ef744b8e2c4d)

Dark theme:
![image](https://github.com/mikebarlow/megaphone/assets/41286822/57094a53-3ea4-4ef7-81ec-2a624ab2e63a)
![image](https://github.com/mikebarlow/megaphone/assets/41286822/2657cbf3-52c9-4f61-872c-1b64ad24d352)

**Comment by titonova** [comment]
@mikebarlow

**Comment by mikebarlow** [comment]
Yeah, sure. As long as it's a separate PR from the wire poll PR that would be awesome.

**Comment by mikebarlow** [comment]
Closing this as I see there are the UI updates in the PR you have opened.
