### ISSUE TITLE
Livewire 3

### ISSUE THREAD

**Issue by gregorysouzasilva** [mikebarlow/megaphone#24]
Hello,
any plans to update to livewire 3? or does it have a fork with the new version?

Tks

**Comment by mikebarlow** [comment]
Hey, yeah I do plan on doing updating to Livewire 3, I've just not had a chance yet. 
I will accept PRs though if you fancy tackling it or if you do spot anyone that has already forked and got it all updated!

**Comment by gregorysouzasilva** [comment]
@mikebarlow thank you. If I have some time I'll take a look.

**Comment by titonova** [comment]
@mikebarlow, @gregorysouzasilva has made a pull request for a livewire 3 update. It looks good

**Comment by mikebarlow** [comment]
Yeah, it's all looking good. The PR is now at #28 

I've branched off from @gregorysouzasilva initial work, got the tests working and updated the readmes.
I will run through the megaphone demo app, get that upgraded, and use that as a test bed for any issues that may have slipped through the test suite.

Looking to get that done tomorrow night (Mon 11th), so Megaphone update should also be released all being well.

**Comment by mikebarlow** [comment]
https://github.com/mikebarlow/megaphone/releases/tag/2.0.0
