### ISSUE TITLE
Anonymous User Notifications

### ISSUE THREAD

**Issue by GiygasForPresident** [mikebarlow/megaphone#25]
Please add a feature to allow all visitors to be notified, whether or not they are logged in.

**Comment by mikebarlow** [comment]
Do you mean, implementing something like email notifications so a user will also get an email as well as the main notification?

Or do you mean, someone who doesn't even have an account should be able to see the notifications?

**Comment by GiygasForPresident** [comment]
I mean, both of those are great. Letting a person subscribe to email notifications and have it sent to emails, but my main idea was to have toast notifications and if the view as read button on the toast notification clicked, it marks it as read and it goes to the notification bell, but otherwise, the toast fades out and the bell will light up.

**Comment by titonova** [comment]
@GiygasForPresident Did you eventually implement this?

**Comment by mikebarlow** [comment]
Right, I think i understand what you meant now. I misunderstood your first message.

Something like that is definitely possible I think. It would need to be tied in with the wire:poll / event subscription type update discussed in issue #12.

**Comment by mikebarlow** [comment]
Going to close this off. After thinking on this, I'm not sure it's the right fit at the moment. Happy to look again if some more use-cases can be brought forward. I'd even look at a PR if you fancied tackling it yourself.
