### ISSUE TITLE
Route

### ISSUE THREAD

**Issue by GiygasForPresident** [mikebarlow/megaphone#26]
Hey, I'm trying to make an entire page where people can see their notifications, not just from a popout, how do I implement this?

**Comment by mikebarlow** [comment]
Under the hood, Megaphone is just using Laravels default notifications systems.

All you need to do is create a route in your application and access the notifications as described in the documentation https://laravel.com/docs/10.x/notifications#accessing-the-notifications

The only difference you should make is that when pulling the notification relationships from your model, use the "announcements()" method which is added to the model via the [HasMegaphone Trait](https://github.com/mikebarlow/megaphone/blob/main/src/HasMegaphone.php).

If you want to introduce other features like the mark as read functionality, you'll likely need to create your page as a Livewire component and duplicate some of the functionality found in the [Megaphone Livewire component](https://github.com/mikebarlow/megaphone/blob/main/src/Livewire/Megaphone.php).
