### ISSUE TITLE
Wire:poll

### ISSUE THREAD

**Issue by digimumo** [mikebarlow/megaphone#36]
I would like to user wire:poll for a quick fix until I get Reverb up and running. I can't figure out where I should place 'wire:poll' 

Ive tried everywhere yet it appears to not update? Any suggestions please?

Ive tried on the megaphone component and also  around the icon count.

```
    <span wire:poll
                aria-label="unread count" class="absolute top-0 left-0 aspect-square max-h-fit rounded-full border-2 bg-red-500 px-1.5 shadow leading-5 text-white font-semibold text-xs">
                {{ $unread->count() }}
            </span>
```

Thanks, Digimumo

**Comment by mikebarlow** [comment]
Hey sorry for the delay in replying to this.
If you keep an eye on the repo tomorrow, i'll hopefully be pushing out an update to Megaphone tomorrow night (UK Time) and wire:poll will be an option in the config!
